import { generateDummyPassword } from "./db/utils";

export const isProductionEnvironment = process.env.NODE_ENV === "production";
export const isDevelopmentEnvironment = process.env.NODE_ENV === "development";
export const isTestEnvironment = Boolean(
  process.env.PLAYWRIGHT_TEST_BASE_URL ||
    process.env.PLAYWRIGHT ||
    process.env.CI_PLAYWRIGHT
);

export const guestRegex = /^guest-\d+$/;

export const DUMMY_PASSWORD = generateDummyPassword();

/**
 * System user IDs for actor tracking in SPLM bitemporal tables.
 * These UUIDs identify which actor (human, chat AI, MCP agent) maintained each version row.
 * Generated by the add-system-users.sql migration; stored in .env.local.
 */
export const CHAT_ASSISTANT_USER_ID = process.env.CHAT_ASSISTANT_USER_ID;
export const MCP_ASSISTANT_USER_ID = process.env.MCP_ASSISTANT_USER_ID;
